spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/my_test?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

    #mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:/mybatis/mappers/*.xml
  # 配置Mybatis数据返回类型别名（默认别名为类名）
  type-aliases-package: com.yunnuo.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

    #配置控制台打印日志Debug
logging:
  level:
    com.jd.mapper: debug